### ISSUE TITLE
Feat: Add zone “conditioning” status to entity

### ISSUE THREAD

**Issue by Gthubln060920** [dahlb/ha_carrier#115]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Debug log shows the API is returning a “conditioning” status for each zone. (I only have Zone1)
The status shows values such as: idle, prep_cool, active_cool, active_heat

### Describe the solution you'd like

Can we get that status exposed to Home Assistant for dashboard and history?

### Describe alternatives you've considered

Not sure how to parse zone data 

### Additional context

 "status": {
          "outdoor_temperature": 70.0,
          "mode": "cool",
          "temperature_unit": "F",
          "filter_used": 30,
          "is_disconnected": false,
          "airflow_cfm": 525,
          "outdoor_unit_operational_status": "off",
          "indoor_unit_operational_status": "off",
          "time_stamp": "06/04/2024, 20:13:43 CDT",
          "zones": [
            {
              "id": "1",
              "name": "ZONE 1",
              "current_activity": "home",
              "temperature": 76.0,
              "humidity": 52,
              "fan": "low",
              "hold": false,
              "occupancy": false,
              "hold_until": null,
              "heat_set_point": 68.0,
              "cool_set_point": 77.0,
              "conditioning": "prep_cool"
            }

**Comment by dahlb** [comment]
already supported, add a templated sensor
```
template:
  - sensor:
      - name: "Airflow CFM"
        unit_of_measurement: "CFM"
        state: '{{ state_attr("climate.hvac_zone_1", "airflow_cfm") }}'
      - name: "AC Status"
        state: '{{ state_attr("climate.hvac_zone_1", "outdoor_unit_operational_status") }}'
      - name: "Heating Status"
        state: '{{ state_attr("climate.hvac_zone_1", "indoor_unit_operational_status") }}'
```
