### ISSUE TITLE
Can't set temperatures or HVAC mode via Service

### ISSUE THREAD

**Issue by jspadea** [dahlb/ha_carrier#8]
Thanks for the integration!  At first I tried to set the preset_mode to away using the Device Action and that didn't work.  I then changed my automation to us the Climate Service instead and that worked.  Then, using the the climate service, I tried to set the HVAC mode to Heat/Cool but that isn't working.  My system has 2 zones: 1st floor and 2nd floor (1 system).

**Comment by dahlb** [comment]
I'm not sure what device action you tried but this service call is what i use is
```
service: climate.set_preset_mode
data:
  preset_mode: Home
target:
  entity_id: climate.hvac_zone_1
```
set mode to heat/cool
```
service: climate.set_hvac_mode
data:
  hvac_mode: heat_cool
target:
  entity_id: climate.hvac_zone_1
```

check the readme for how to enable debug logging, if you post the service calls you are making with their related carrier_api and ha_carrier logs we can likely resolve your issue
